# Generated by AmhaScript Translator v1.0
# Adama Science and Technology University — CSEg 4306

def ደምር(a, b):
    return (a + b)

def ቀነስ(a, b):
    return (a - b)

def አባዛ(a, b):
    return (a * b)

def ክፈል(a, b):
    if (b == 0):
        print(0)
        return 0
    else:
        return (a / b)

num1 = 20
num2 = 4
addition = ደምር(num1, num2)
subtraction = ቀነስ(num1, num2)
multiply = አባዛ(num1, num2)
division = ክፈል(num1, num2)
print(addition)
print(subtraction)
print(multiply)
print(division)
