# Generated by AmhaScript Translator v1.0
# Adama Science and Technology University — CSEg 4306

count = 1
while (count < 6):
    print(count)
    count = (count + 1)
n = 7
if (n > 5):
    print(n)
else:
    print(0)
