# Generated by AmhaScript Translator v1.0
# Adama Science and Technology University — CSEg 4306

def demr(a, b):
    return (a + b)

def absolute(n):
    if (n > 0):
        return n
    else:
        return (0 - n)

wetaet = demr(4, 6)
print(wetaet)
absval = absolute((0 - 9))
print(absval)
