# Generated by AmhaScript Translator v1.0
# Adama Science and Technology University — CSEg 4306

x = 10
y = 3
dmr = (x + y)
lynt = (x - y)
qlit = (x * y)
print(dmr)
print(lynt)
print(qlit)
